# Settings for the app
app:
  # HTML Title
  title: Air.HeyDuwamish
  # Site Link
  link: Air.HeyDuwamish
  # Header name
  name: Air.HeyDuwamish
  # Meta description that will show up in Google search results
  meta_description: _(Duwamish Air!)
  # Meta author that will show up in Google search results
  meta_author: SmarterCleanup.org


  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

languages:

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  geocoding_enabled: true # enable general geocoding features (ie geocoded place fields)
  geocoding_bar_enabled: false # add a geocode bar across the map
  geocode_bounding_box: [45.2, -125, 49.3, -116.4] # Including cushion

  counter: false
  counter_min: 0
  counter_max: 1000

  options:
    center:
      lat: 47.61345
      lng: -122.29843
    zoom: 11
    minZoom: 7
    maxZoom: 18
    maxBounds: [[45.2, -125], [49.3, -116.4]] # Including cushion
  layers:
    - url: //{s}.tiles.mapbox.com/v4/smartercleanup.m1b2emco/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      visible: true
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'


  # Map Layers

    - id: esri-air
      url: //services.arcgis.com/qboYD3ru0louQq4F/arcgis/rest/services/Duwamish_061415/FeatureServer/0/query?f=geojson&geometry={%22xmin%22:-126,%22ymin%22:43.2,%22xmax%22:-114.4,%22ymax%22:51.3,%22spatialReference%22:{%22wkid%22:4326}}&geometryType=esriGeometryEnvelope&inSR=2926&outFields=*&outSR=4326
      type: json
      # type: esri
      description: _(Air Concerns from esri map)
      popupContent: '{{Comments}}'
      legend: true
      visible: true
      title: _(Air Concerns)
      rules:

        # default point marker case
        - condition: 'true'
          icon:
            iconUrl: /static/css/images/markers/triangle-2654d2.png
            iconSize: [16, 16]
            iconAnchor: [8, 8]

    - id: mapbox-pscaa
      # url: //a.tiles.mapbox.com/v4/smartercleanup.k9dcl2i9/features.json?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      url: //a.tiles.mapbox.com/v4/smartercleanup.njpe7ha8/features.json?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      type: json
      description: _(Air Monitoring Stations by PSCAA)
      popupContent: '{{title}}'
      legend: true
      visible: true
      title: _(Air Monitoring)
      rules:
        # - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "danger"'
        #   icon:
        #     iconUrl: /static/css/images/markers/marker-construction.png
        #     iconSize: [30, 30]
        #     iconAnchor: [15, 15]

        # - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "park2"'
        #   icon:
        #     iconUrl: /static/css/images/markers/marker-treeheart.png
        #     iconSize: [40, 40]
        #     iconAnchor: [13, 13]

        # - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "industrial"'
        #   icon:
        #     iconUrl: /static/css/images/markers/marker-industrial.png
        #     iconSize: [40, 40]
        #     iconAnchor: [20, 20]

        # - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "bicycle"'
        #   icon:
        #     iconUrl: /static/css/images/markers/marker-bike.png
        #     iconSize: [30, 30]
        #     iconAnchor: [15, 15]

        # default point marker case
        - condition: 'true'
          icon:
            iconUrl: /static/css/images/markers/dot-fa307d.png
            iconSize: [16, 16]
            iconAnchor: [8, 8]

      # WMS landuse
    - id: geoserver-landuse
      url: http://heyduwamish.org:8080/geoserver/wria9/wms
      layers: 'wria9:Landuse2010'
      version: '1.1.0'
      transparent: 'true'
      format: 'image/png'
      legend: true
      opacity: 0.5
      description: <img src="/static/css/images/legend-landuse2010.png" alt="legend">
      title: _(Zoning info)
      visible: false

      # WMS Buildings connection:
    - id: geoserver-buildings
      url: http://heyduwamish.org:8080/geoserver/wria9/wms # GCE Geoserver
      layers: 'wria9:2009BuildingsCOS'
      version: '1.1.0'
      transparent: 'true'
      format: 'image/png'
      legend: true
      description: _(legend coming soon!)
      title: _(Buildings)
      visible: false

      # WMS Original Flow
    - id: duwamish-original
      url: //d171ntg776wsmz.cloudfront.net/geoserver/wria9/wms
      layers: 'wria9:Historical_Flow'
      version: '1.1.0'
      transparent: 'true'
      format: 'image/png'
      legend: true
      opacity: 0.4
      description: _(The orginal Duwamish River path)
      title: _(Original river path)
      visible: false

#      # WMS NLCD (commented out for parks)
#    - url: http://heyduwamish.org:8080/geoserver/wria9/wms
#      layers: 'wria9:nlcd2011'
#      version: '1.1.0'
#      transparent: 'true'
#      format: 'image/png'
#      legend: true
#      opacity: 0.6
#      description: "_(key: <br>-The red area means more concrete coverage<br>-blue means water<br>-dark green means forested<br>-light green means grass or soil)"
#      description: <img src="/static/css/images/legend-nlcd2011.png" alt="legend">
#      title: _(Land covereage data)
#      visible: false


  # Report filters

    - title: _(Rain gardens)
      shareabouts: true
      image: /static/css/images/markers/marker-observation.png
      url: /filter/raingarden
      external: true
      visible: true

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:

  observation:
    label: _(Observation)
    rules:
      - condition: '"{{location_type}}" === "observation" && {{map.zoom}} < 11 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '"{{location_type}}" === "observation" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          iconSize: [24, 29]
          iconAnchor: [12, 29]

      - condition: '"{{location_type}}" === "observation" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

      - condition: '"{{location_type}}" === "observation" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

  question:
    label: _(Question)
    rules:
      - condition: '"{{location_type}}" === "question" && {{map.zoom}} < 11 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '"{{location_type}}" === "question" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          iconSize: [24, 29]
          iconAnchor: [12, 29]

      - condition: '"{{location_type}}" === "question" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

      - condition: '"{{location_type}}" === "question" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]
#      - condition: '"{{location_type}}" === "question" && {{layer.focused}}'
#        icon:
#          iconUrl: /static/css/images/markers/marker-question.png
#          shadowUrl: /static/css/images/marker-shadow.png
#          iconSize: [50, 60]
#          shadowSize: [50, 60]
#          shadowAnchor: [25, 60]
#          iconAnchor: [25, 60]
#
#      - condition: '"{{location_type}}" === "question"'
#        # Show questions that are points as icons...
#
#        icon:
#          iconUrl: /static/css/images/markers/marker-question.png
#          iconSize: [24, 29]
#          iconAnchor: [12, 29]
#
#        # ...and questions that are polygons as shapes.
#
#        style:
#          color: '#4bbd45'
#          weight: 1
#          opacity: 0.9
#          fillOpacity: 0.4

  idea:
    label: _(Idea)
    rules:
      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} < 11 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          iconSize: [24, 29]
          iconAnchor: [12, 29]

      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

      - condition: '"{{location_type}}" === "idea" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]
#      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} < 13 && {{layer.focused}} === false'
#        # Display landmarks as circles (vectors) when zoomed out
#
#        style:
#          color: '#0d85e9'
#          radius: 3
#          weight: 1
#          opacity: 0.9
#          fillOpacity: 1
#
#      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
#        # Display landmarks as icons when zoomed in
#
#        icon:
#          iconUrl: /static/css/images/markers/marker-idea.png
#          iconSize: [50, 60]
#          iconAnchor: [24, 59]
#
#      - condition: '"{{location_type}}" === "idea" && {{layer.focused}} === true'
#        # Display landmarks as icons when zoomed in
#
#        icon:
#          iconUrl: /static/css/images/markers/marker-idea.png
#          shadowUrl: /static/css/images/marker-shadow.png
#          iconSize: [80, 96]
#          shadowSize: [41, 41]
#          iconAnchor: [39, 94]

  complaint:
    label: _(Complaint)
    rules:
      - condition: '"{{location_type}}" === "complaint" && {{map.zoom}} < 11 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '"{{location_type}}" === "complaint" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [24, 29]
          iconAnchor: [12, 29]

      - condition: '"{{location_type}}" === "complaint" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

      - condition: '"{{location_type}}" === "complaint" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

# TODO: Create data visualization where a cluster represents it location type makeup
cluster:
  threshold: 100
  class_small: cluster-small
  class_large: cluster-large
  size_small: 40
  size_large: 60

# Sidebar and activity stream should be enabled and disabled together!
# note: sidebar is aka 'MasterLegend'
# TODO: Couple the sidebar and activity stream because the activity stream is a component of the sidebar
sidebar:
  enabled: true
  legend_enabled: true
  slug: filter-type
  # Layers are defined in the "map config" section
  # TODO: Refactor the Layers section into its own sidebar
  layersTitle: _(Map Layers)
  reports:
    title: _(Report Types)
    items:
      - title: _(Observations)
        image: /static/css/images/markers/marker-observation.png
        url: /filter/observation
      - title: _(Ideas)
        image: /static/css/images/markers/marker-idea.png
        url: /filter/idea
      - title: _(Questions)
        image: /static/css/images/markers/marker-question.png
        url: /filter/question
      - title: _(Complaints)
        image: /static/css/images/markers/marker-complaint.png
        url: /filter/complaint
      - title: _(Hide Reports)
        url: /filter/none
        image: /static/css/images/hide-all.png
      - title: _(Show Reports)
        url: /
        image: /static/css/images/show-all.png

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

  # Place Types

place:
  adding_supported: true
  add_button_label: _(Add your air concern to the map)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(Show as a list)
  show_map_button_label: _(Back to the Map)
  action_text: _(added)
  title: _(Add your air concern to the map)
  action_text: _(added)
  anonymous_name: _(Anonymous)
  submit_button_label: _(Put it on the map!)

  location_item_name: Address

  items:
    - prompt: _(Rain garden location)
      type: geocoding
      name: private-rain_garden_address
      optional:
      attrs:
        - key: placeholder
          value: _(Please type full address, (will not be published))
        - key: size
          value: 30
    - prompt: _(Garden Name)
      label: _(Garden Name:)
      type: text
      name: rain_garden_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Garden Name)
        - key: size
          value: 30
    - prompt: _(Rain garden size (square feet))
      label: _(Rain garden size (square feet):)
      type: text
      name: rain_garden_size
      sticky: true
      attrs:
        - key: placeholder
          value: _(Approximate square footage?)
        - key: size
          value: 30
    - prompt: _(Size of contributing area)
      label: _(Size of contributing area:)
      type: text
      name: contributing_area
      optional:
      sticky: true
      attrs:
        - key: placeholder
          value: _(How large is the catchment area that drains to this rain garden?)
        - key: size
          value: 30
    - prompt: _(Description)
      label: _(Description:)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Any notes you want to add for others would be wonderful :))
    - name: location_type
      type: hidden
      value: raingarden
    - prompt: _(Primary sources)
      label: _(Sources:)
      type: checkbox-list
      name: sources
      attrs:
        - label: _(Roof)
          value: roof
        - label: _(Pavement)
          value: pavement
        - label: _(Other)
          value: other
    - prompt: _(Designer)
      label: _(Designer:)
      type: text
      name: designer
      optional:
      sticky: true
      attrs:
        - key: placeholder
          value: _(Designed by?)
        - key: size
          value: 30
    - prompt: _(Installer)
      label: _(Installer:)
      type: text
      name: installer
      optional:
      sticky: true
      attrs:
        - key: placeholder
          value: _(Installed by?)
        - key: size
          value: 30
    - prompt: _(Contributor's name)
      label: _(Contributor's name:)
      type: text
      name: contributor_name
      optional:
      sticky: true
      attrs:
        - key: placeholder
          value: _(Who should we give credit to?)
        - key: size
          value: 30
    - prompt: _(Your Email)
      type: text
      name: private-contributor_email
      optional:
      sticky: true
      attrs:
        - key: required
          value: _(Your email address is kept private and will not be published)
        - key: size
          value: 30
    - prompt:
      inputfile_label: _(Please add an image)
      type: file
      name: my_image
      optional:
      attrs:
        - key: accept
          value: image/*

survey:
  submission_type: comments

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  submit_btn_text: _(Like)
  response_name: _(like)
  response_plural_name: _(likes)
  action_text: liked
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true

  - title: _(Background)
    slug: background
    name: background

  - title: _(Contribute)
    slug: contribute
    name: contribute